### ISSUE TITLE
Intellisense support for sapui5

### ISSUE THREAD

**Issue by kadir950** [asebak/UI5-VisualStudioPlugin#3]
Hi,
Thanks for your development. When will you publish Javascript intellisense support for sapui5 framework? (Now it is difficult to work with sapui5 on visual studio without intellisense )

What is the release date for "Javascript intellisense for the framework" feature?

**Comment by asebak** [comment]
It's an open source plugin so feel free if you would like to do that to add it to this project.  To be honest visual studio provides the intellisense once you reference the sapui core libraries.  I always wanted to add intellisense and visual gui editor for the sap ui5 views for both the vs and intellij plugin I created but I just didn't have enough time(got other projects going on).

**Comment by asebak** [comment]
I might work on it in the future depends if other people help out

**Comment by asebak** [comment]
just finished this, its not the best intellisense but should do for the basic namespaces.
